// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LhU5E-3uDUiej1kZ0JK4owNbSjem16U',
    appId: '1:352449067824:web:921d82847660324f7d26f5',
    messagingSenderId: '352449067824',
    projectId: 'flutter-parker-app',
    authDomain: 'flutter-parker-app.firebaseapp.com',
    storageBucket: 'flutter-parker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBTBJsdWiXp_mj0D7hIdZqWqxAbYSC99o',
    appId: '1:352449067824:android:c140df63d53de7397d26f5',
    messagingSenderId: '352449067824',
    projectId: 'flutter-parker-app',
    storageBucket: 'flutter-parker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBRWZNIYhbpiXEddzIgol68ijwtRsMhgU',
    appId: '1:352449067824:ios:5b12a027a0de245f7d26f5',
    messagingSenderId: '352449067824',
    projectId: 'flutter-parker-app',
    storageBucket: 'flutter-parker-app.firebasestorage.app',
    iosBundleId: 'com.example.parker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBRWZNIYhbpiXEddzIgol68ijwtRsMhgU',
    appId: '1:352449067824:ios:5b12a027a0de245f7d26f5',
    messagingSenderId: '352449067824',
    projectId: 'flutter-parker-app',
    storageBucket: 'flutter-parker-app.firebasestorage.app',
    iosBundleId: 'com.example.parker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3LhU5E-3uDUiej1kZ0JK4owNbSjem16U',
    appId: '1:352449067824:web:10d593a5c07d47dd7d26f5',
    messagingSenderId: '352449067824',
    projectId: 'flutter-parker-app',
    authDomain: 'flutter-parker-app.firebaseapp.com',
    storageBucket: 'flutter-parker-app.firebasestorage.app',
  );
}
